### ISSUE TITLE
Add the Mega apk file here on GitHub

### ISSUE THREAD

**Issue by ghost** [meganz/android#100]
Hello when you release a new version. Can you add the apk file under GitHub releases?
https://github.com/meganz/android/releases

**Comment by bingoxo** [comment]
why is this still not implemented ?

**Comment by javiergm1983** [comment]
Hi, we will try to start doing it in the following releases.

**Comment by bingoxo** [comment]
> Hi, we will try to start doing it in the following releases.

can you release each arch separately please ? so it's  smaller size and easier to verify the build
