### ISSUE TITLE
[Bug] Unable to change notification sound for incoming messages

### ISSUE THREAD

**Issue by PlayfulThomas** [meganz/android#105]
I am unable to change the notification sound for chat messages on my Mega client. Changing the value from _Mega -> Menu -> Settings -> Notifications : Chat -> Message sound_ does not work, but the system-wide setting on _Android : Settings -> Sound -> Additional -> Default sound for notification_ is used instead. (Menu path translated from other language, terms might be different in English.)

Does anyone else have this problem? Is there any workaround or fix to it? I was able to set different sound for notifications for WhatsApp Messenger 2.20.108, so this shouldn't be a system-wide issue on my phone.

Mega 3.7.4 (297)
Android 9
Nokia 5 TA-1053

**Comment by PlayfulThomas** [comment]
This seems to be fixed in recently published version of 3.7.5 (305). I wonder if this issue had any effect on it though, as it is still open and there has been no visible developer activity. Is anyone from Mega Ltd. reading these issues, or is there an alternate preferred channel to deliver bug reports and suggestions for new features and enhancements?

**Comment by javiergm1983** [comment]
Hi @PlayfulThomas, of course we read all the problems and messages, but we cannot give an immediate answer to all, and before close any issue we like to confirm that it is really solved.
Thank you for confirming that the problem is solved.

**Comment by PlayfulThomas** [comment]
The same issue is present in my new Samsung Galaxy A32 device. Notification sound selected in _Mega > Menu > Settings > Notifications : Chat > Message sound_ doesn't work, but system-wide notification sound of _Settings > Sounds and vibration > Notification sound : SIM1_ is used.

## General Information

- **MEGA Version:** 
6.4 (430)
- **OS Version(s):** 
Android 11, One UI 3.1
- **Devices/Simulators:** 
Samsung Galaxy A32 SM-A326B/DS
- **Reproducible? (Yes/No):** 
Yes

**Comment by PlayfulThomas** [comment]
I seem to be unable to reopen this issue as it was not closed by me.

**Comment by javiergm1983** [comment]
Hi, we already have it in our tracklist. We will try to investigate it and solve it in a future version.
