### ISSUE TITLE
[Bug] Incoming Mega call alarms under Do Not Disturb (DND) -mode

### ISSUE THREAD

**Issue by PlayfulThomas** [meganz/android#111]
Incoming Mega call seems to alarm even though phone is set to Do Not Disturb (DND) mode.

There is a setting in _Mega_ -> _Settings_ -> _Notifications: Chat_ -> _Additional_ -> _Bypass Do Not Disturb_ -setting, but I suppose this is for notifications only, not for calls, and it is set to off.

On my Android, I have set at _Settings_ -> _Sound_ -> _Do Not Disturb_ -> _Exceptions : Calls_ -> _Allow calls: Only from starred contacts_. On the same _Do Not Disturb_ -dialog, under _Behavior : Sound and vibration_ -> _Alarms_ and _Media_ are allowed, _Touch(?) sounds_ not allowed.

I would imagine that these settings should also mute incoming Mega calls. The person calling me is not marked as starred in my contacts list.

Mega 3.7.5 (307)
Android 9
Nokia 5 TA-1053

**Comment by javiergm1983** [comment]
Hi, thanks for report it but as you said these settings are for notifications not for calls.
Anyway we are working on improve our DND mode, so I hope you could see some improvements very soon.

**Comment by PlayfulThomas** [comment]
> Hi, thanks for report it but as you said these settings are for notifications not for calls.
> Anyway we are working on improve our DND mode, so I hope you could see some improvements very soon.

Any update in sight on this? Mega is still playing ringtone for incoming calls under DND mode on 4.1.2 (372).
