### ISSUE TITLE
[Bug] Unable to access application (Offline state) without network connection

### ISSUE THREAD

**Issue by PlayfulThomas** [meganz/android#112]
In Mega 3.7.4 (297) and below, if both WiFi and mobile data of the phone were disabled, or WiFi access was rejected, Mega app started in offline state, offering one to browse files saved for offline use and type chat messages for existing conversations to be delivered when network connection returns.

However, in 3.7.5 (307) this seems to have changed so, that even when there is no WiFi connection present, or it is turned off from Android settings, Mega is still trying to connect the server, saying eventually

> Unable to reach MEGA. Please check your connectivity or try again later,

and keeps trying to connect, without starting the app in offline state.

Mega 3.7.5 (307)
Android 9
Nokia 5 TA-1053

**Comment by javiergm1983** [comment]
Hi @PlayfulThomas, thanks for report it. We will try to fix it as soon as possible.

**Comment by javiergm1983** [comment]
I confirm that the fix will be included since the v3.7.6 (310).

**Comment by PlayfulThomas** [comment]
@javiergm1983, I have not yet received an update from Google Play. The app shows on my Android device that the latest version would be still 3.7.5 (307), updated at 27th of May, although https://play.google.com/store/apps/details?id=mega.privacy.android.app&hl=en shows that it would have been updated 9th of June.

**Comment by javiergm1983** [comment]
Yes, we started the production roll out process on 9th June. It should be available for the 100% of users along today.

**Comment by PlayfulThomas** [comment]
I confirm this issue is resolved in my device by v3.7.6 (310).
