### ISSUE TITLE
[Bug] Statuses not shown, conversations not being loaded

### ISSUE THREAD

**Issue by PlayfulThomas** [meganz/android#123]
## General Information

- **MEGA Version:** 3.7.7 (318)

- **OS Version(s):** Android 9

- **Devices/Simulators:** Nokia 5 TA-1053

- **Reproducible? (Yes/No):** Yes

##  What happened?
When opening chat view, conversations are not being loaded, instead "Loading conversations..." message is shown. If there are new messages, a small "1" is shown on the bottom panel on chat symbol. Below "CHAT" -topic, there is a "Connecting..." -message. If one clicks this message, a status view will open, but setting any of the statuses gives an error message to the bottom, saying "Error. Your status has not been changed".

One can get to conversation view through the menu, by clicking the three lines > Contacts > (Select a contact) > Message. On this view, recipients status is not either shown, instead, "Reconnecting to chat" message is being displayed. Chat messages themselves are working in both directions. Buttons for audio and video call are inactive.

## What did you expect to happen?
In chat view, conversations should be loaded. Status should be shown and one should be able to change it from the view opening by clicking it.

In conversation view, one should see recipients status. Buttons for audio and video calls should be enabled.

I would suspect this being a server-side issue, as for status not displaying, it seems to be present in web application and iOS too. This issue has been around for couple days for now.

**Comment by javiergm1983** [comment]
Hi @PlayfulThomas, as you said this is a server side issue and we are working to fix it.
Try to kill the app and open it again to see if that solves the issue for you. Please let us know when you detect the issue is fixed and chat works again. Thanks.

**Comment by PlayfulThomas** [comment]
This issue seems to be fixed now in all aspects.
