### ISSUE TITLE
'Downloading file' notification STUCK

### ISSUE THREAD

**Issue by pilsnerbeer** [meganz/android#130]
## General Information

- **MEGA Version:**  3.8.5

- **OS Version(s):**  10

- **Devices/Simulators:**  OP5T

- **Reproducible? (Yes/No):**  not always

##  What happened?
1) download a file from app
2) notification with progress will show up as the file is being downloaded
3) downloading finished but notification still there. cannot be swiped away. App must be manually stopped.
(this happened to me many times since I started using Mega (few weeks) but it doesn't happen 100% of the time).

## What did you expect to happen?
downloading finishes, notification changes to 'downloading finished..' and user can swipe it away.

Picture of stuck notification: (tried downloading 1 file, notification says '2 of 1 file' which doesn't make sense to me.)

![notif](https://user-images.githubusercontent.com/36133540/107546847-19c8f480-6bcd-11eb-9d5a-a1957e741f22.jpg)

**Comment by sakethv-mega** [comment]
Hello there, a fix for this issue has already being worked on. It will be out with the next app update. Thank you.

**Comment by KdB13** [comment]
@sakethv-mega Could you please tell in which version of MEGA this issue is fixed?
