### ISSUE TITLE
[Feature request] Mega should rotate outgoing video to landscape when sending device being turned to landscape

### ISSUE THREAD

**Issue by PlayfulThomas** [meganz/android#142]
## General Information

- **MEGA Version:** 4.1.2 (372)

- **OS Version(s):** Android 9, 10

- **Devices/Simulators:** Huawei P20 Pro CLT-L29, Nokia 5 TA-1053

- **Reproducible? (Yes/No):** Yes

##  What happened?

If the other participant of the video call rotates his device to from portrait to landscape, sending video is not turned to landscape, but instead turned just statically. This happens even when automatic rotate detection on Android is on.

## What did you expect to happen?

Mega should rotate the sending video to landscape when sending device being rotated. Mega on iPad is doing this correctly.

**Comment by javiergm1983** [comment]
Thanks for your comment @PlayfulThomas. We are already working on improve it.
