### ISSUE TITLE
[IDEA] Mega Photos

### ISSUE THREAD

**Issue by pluja** [meganz/android#143]
It would be awesome if MEGA had a dedicated app or dedicated section with powerful (and open source) photo management. The ability to create albums, see photos by date and location and maybe even object/scenario recognition (obviously with privacy in mind). I don't know if this could be a thing, but it is definetelly something that I would love to see in MEGA.

**Comment by javiergm1983** [comment]
Thanks for your comment @pluja. We are working on improve that section.
