### ISSUE TITLE
Feature Request : Add Seperare Category for Favorites and Labels 

### ISSUE THREAD

**Issue by KonstantMan** [meganz/android#148]
I recently started using mega moving from Google drive to  a more private solution, so far I have no problem except from the fact that I can't organize my pictures as I want especially in android. You can add labels or add an image to favorites, but there is no option to view favorites or each label separately it might be because I'm on the free plan but still it's a very basic feature and very useful when you have a lot of pictures to back up.

Please add a way to see labels and favorites seperatly since you already have the section where you can see the different formats of files you have,which is useful for sure but it's not a great way to categorize 500 pictures. 

![Screenshot_2021-06-27-20-13-34.png](https://user-images.githubusercontent.com/56481040/123553532-64b26580-d784-11eb-8f2c-d627f47a58da.png)

Android Version 8.0
![Screenshot_2021-06-27-19-57-49.png](https://user-images.githubusercontent.com/56481040/123553158-464b6a80-d782-11eb-86a5-44997195c9d6.png)

**Comment by sakethv-mega** [comment]
Hello there, thank you for your suggestion.
We are already working on a similar feature and revamping the whole photos project and you will see a lot of new changes in that area.
We aim to roll out those features in the next couple of months. Stay tuned.

**Comment by KonstantMan** [comment]
Any updates?

**Comment by sakethv-mega** [comment]
Hello, we don't have an exact timeline of updates on this project yet. Thank you.
