### ISSUE TITLE
[Bug] Can't open url file on other browser than Chrome

### ISSUE THREAD

**Issue by paulverbeke** [meganz/android#162]
## General Information
Hi, I'm currently reviewing the MEGA app as an alternative to Dropbox. You've done a great job the app looks great ❤️.

- **MEGA Version:** 
5.0(406)
- **OS Version(s):** 
Android 12
- **Devices/Simulators:** 
OnePlus 8T
- **Reproducible? (Yes/No):** 
Yes
##  What happened?
When trying to open (by click or by Open With) an *.url file, the app says that I don't have any apps installed that support this file type. Ex: 
![Screenshot_20210930-064237](https://user-images.githubusercontent.com/6412153/135389158-998ba61f-299d-4b9a-93e4-220f1deb1f4a.jpg)

## What did you expect to happen?
I would expect the MEGA app to open the corresponding link in my default browser like Dropbox.

**Comment by Yenel** [comment]
Hi @paulverbeke, we have checked that behaviour and MEGA app can open `*.url` files without any problem in Android 12. 
Which I can see in the image you attached is, the file you are trying to open is not `*.url`, but *.ur`, so the app cannot identify it as an url file. Maybe you renamed by mistake the file. Could you check if renaming it again by `*.url` works as expected?

Thank you!

**Comment by paulverbeke** [comment]
Hi thanks for the answer.
Yes I noticed that, but as I specifically imported an url file, and because of these screenshots, I figured that was just a display bug![](https://i.imgur.com/0H0S5d7.jpg)![](https://i.imgur.com/wSTLzN3.jpg)![](https://i.imgur.com/E3VRdsk.jpg)

**Comment by paulverbeke** [comment]
Hello @Yenel, thanks for taking the time. I see that in the video you're saving the link from Firefox but opening it from MEGA opens it in Chrome.
I personally have Chrome disabled on my phone and Firefox as default browser.
I tested your exact use case: re-enabled Chrome, and put Chrome as default browser. Opening the link now works and opens in Chrome, but I definitely want to use Firefox as default browser. You can see here that in the prompt that now works, I can't even see any other browser than Chrome. I can't see Firefox, Tor, or DuckDuckGo that are all installed
![](https://i.imgur.com/UVDnYrs.jpg)

**Comment by paulverbeke** [comment]
Hi all, I just tested and can confirm it's fixed, thanks for your work !
