### ISSUE TITLE
Navigation Buttons barely visible when using audio player

### ISSUE THREAD

**Issue by Pentaphon** [meganz/android#163]
## General Information

- **MEGA Version:** 5.1

- **OS Version(s):** 11

- **Devices/Simulators:** Moto G9

- **Reproducible? (Yes/No):** Yes

##  What happened?
Navigation Buttons barely visible when using audio player

## What did you expect to happen?
I expect to clearly see the navigation buttons no matter what app window I use. 

See screenshot below. Nav Buttons are barely visible under the player. They should be clearly visible. I blurred out the audio title on purpose. 

![buttons](https://user-images.githubusercontent.com/49374058/137348114-43719716-4f9a-4eed-811e-846e632694fc.jpg)

**Comment by sakethv-mega** [comment]
Hello, thank you for the report. 

We are aware that this issue is happening on a few devices but not all.

A bug report has been filed with our developers already and is under investigation.

**Comment by Pentaphon** [comment]
@sakethv-mega the buttons are now showing up on version 5.4 for my Moto phone but I will leave it open until you decide all devices have been fixed. Thanks.

**Comment by javiergm1983** [comment]
@sakethv-mega as @Pentaphon sais we have included the fix in v5.4 for all devices, so I will close this issue.
