### ISSUE TITLE
Long filenames in file lists are shortened with "..." making them hard to read

### ISSUE THREAD

**Issue by Pentaphon** [meganz/android#165]
## General Information

- **MEGA Version:** 5.1

- **OS Version(s):** 11 stock

- **Devices/Simulators:** Moto G9

- **Reproducible? (Yes/No):** Yes

##  What happened?
If you have a long filename on a file list, it gets shortened with "..." making it hard to read on your display and even if you press the info button it still shortens the long filename on Mega links that don't belong to you. 

## What did you expect to happen?
I expect to be able to read the entire filename when browsing a file list. 

Here is a file example I just made. See how you can read the entire name viewing the text file?

![Screenshot_20211024-110611_1](https://user-images.githubusercontent.com/49374058/138607181-55d66269-e6f8-4f33-a253-1ab9bf9c364c.png)

Here is how the filename of the same file when I scroll by it on my file list in my cloud drive. I can't read the whole thing because it is shortened by "...". It should scroll like a marquee to let me read long filenames or at least let me press the info button to display the entire filename for me.

![Screenshot_20211024-110623_1](https://user-images.githubusercontent.com/49374058/138607094-c3b9bbde-7e03-479f-bc87-5216fed44de6.png)

But as you can see...the filename is also shortened when I press the 3-dot button to try to read the entire filename. It should display the entire filename when I press the 3-dot button because there is more space to display it, but nope, it is also shortened. 

![Screenshot_20211024-111145-705](https://user-images.githubusercontent.com/49374058/138607161-8ac9a63f-adcb-4f0d-989f-b7722ec3a960.png)

Also, when viewing the filename when pressing the 3 dot button, the last T in ".txt" is not there. Why is that? It should show the entire file extension, not ".tx"

Continued on next post since I can't seem to post more than 3 screenshots per post on Github....see below.

**Comment by javiergm1983** [comment]
Hi @Pentaphon, the issue has been solved for v5.4 of the app. Please let us to know when you receive that update if the issue is fixed for you. Thanks.

**Comment by Pentaphon** [comment]
The T missing at the end of the extension seems to be fixed as well as the shortened names in the info popup now being much longer. I am satisfied with this. Thanks.
