### ISSUE TITLE
Title and album display sometimes appears blank after pressing next track button

### ISSUE THREAD

**Issue by Pentaphon** [meganz/android#167]
## General Information

- **MEGA Version:** 5.2

- **OS Version(s):** 11

- **Devices/Simulators:** moto g9

- **Reproducible? (Yes/No):** no?

##  What happened?
Title and album display sometimes appear blank after pressing the next track button Only why to make it show up is to tap the notification to go back to the player screen which shows the title and album properly. 

## What did you expect to happen?
I expect the title and album to always be there.  

![blank](https://user-images.githubusercontent.com/49374058/139602496-564d4e5a-4a28-4bc8-aa7b-0dac9e625694.png)

**Comment by angelds-mega** [comment]
Can you please update the MEGA app version to (6.1.1 (242)) for  see if the issue persist? Thank you.

**Comment by Pentaphon** [comment]
I just went through over 100 files by pressing the next button over and over and the title and album display didn't appear blank. The issue seems to have been fixed. Closing issue.
