### ISSUE TITLE
Impossible to call an iOS peer - version_incompatibility

### ISSUE THREAD

**Issue by tosiara** [meganz/android#169]
## General Information

- **MEGA Version:**  Latest PlayStore version 5.2

- **OS Version(s):**  Android 11

- **Devices/Simulators:**  Android One Motorola

- **Reproducible? (Yes/No):**  Yes

##  What happened?
1. Call an iOS peer
2. Call cannot establish and you get a warning:
"We are upgrading MEGAchat. Your calls might not be connected due to version incompatibility unless all parties update their MEGA apps to the latest version."

## What did you expect to happen?
The call worked fine some time ago, expected it to still work

Latest iOS version in App Store is 6.3

**Comment by angelds-mega** [comment]
Hello. 
Can you please update the MEGA app version to (6.1.1 (242)) for Android and (v7.3) for iOS and see if the issue persist? Thank you.

**Comment by tosiara** [comment]
yes, now seems to work. thanks!
