### ISSUE TITLE
biometrics bypass

### ISSUE THREAD

**Issue by bingoxo** [meganz/android#172]
on the version 5.4  using biometick lock , it can be easily bypassed by using back button and allows direct access to user's files , please fix asap

**Comment by javiergm1983** [comment]
Thanks for reporting @bingoxo. We are investigating it and will try to fix it as soon as possible.

**Comment by javiergm1983** [comment]
Hi again @bingoxo, it is fixed in v5.5. Please could you confirm it when you receive that version?

**Comment by bingoxo** [comment]
why isn't it in the releases page ?

i confirm it's working better now

**Comment by javiergm1983** [comment]
> why isn't it in the releases page ?
We just moved it to production today. The version appears now in the releases page.

> i confirm it's working better now
Ok, thanks for confirming. I will close this issue.

**Comment by bingoxo** [comment]
i meant how did it show up in google play before releases page ?

**Comment by javiergm1983** [comment]
Because you received the update very quick from Google Play :smile: 
We published it in releases pages only some minutes after move to production.
