### ISSUE TITLE
Black screen when opening MEGA app

### ISSUE THREAD

**Issue by icstyle** [meganz/android#179]
## General Information

- **MEGA Version:** 
6.1.1
- **OS Version(s):** 
Android 12 (latest Security Update)
- **Devices/Simulators:** 
Pixel 5
- **Reproducible? (Yes/No):** 
Yes
##  What happened?
After last MEGA update, when opening app, I see the logo and after that only a black screen. When clearing Cache/StorageData it works again one time, I can login, enable Camera Sync etc. But after that again black screen. Camera Sync still works though in background.

## What did you expect to happen?
Opening app normally.

**Comment by angelds-mega** [comment]
Hello, our developers are currently investigating the issue.  
We will keep you posted for any updates. We apologise for the inconvenience.

**Comment by augt** [comment]
Same here with a pixel 3a on Android 12. The only solution I found was to install an older version of the app

**Comment by augt** [comment]
I tried out the 6.2 version from apk mirror because I can't find it on the play store. The issue is still there so I'm reverting back to version 6.0

**Comment by icstyle** [comment]
v6.2 Build 427 has fixed the problem for me

**Comment by augt** [comment]
v6.2 build 427 fixed the issue for me too. Thanks for your work.

**Comment by javiergm1983** [comment]
@augt your problem seems to be a different one.
I think would be better if you contact with our support department (support@mega.nz) in order to provide logs, screen recording, etc.

@angelds-mega please could you help on this? Thanks.

**Comment by augt** [comment]
The 6.2 version I tried from apk mirror had the version code 426. The problem seems to be fixed with the 6.2 ( version code 427) version i got today on aptoide.

**Comment by javiergm1983** [comment]
> The 6.2 version I tried from apk mirror had the version code 426. The problem seems to be fixed with the 6.2 ( version code 427) version i got today on aptoide. I don't think it will be necessary for me to contact support, but thanks.

Ok @augt, but we are only responsible for the app obtained from Google Play, Huawei AppGallery or APKs obtained from this repository, so if you are getting the app from any other source, sorry but we are not responsible of any problem you could have.

**Comment by javiergm1983** [comment]
As the issue seems solved, we will close the issue.
Thanks to everyone for the collaboration.

**Comment by augt** [comment]
Ok I didn't know that it was possible to download the apk from this repo. Have a good day.
