### ISSUE TITLE
video fail to play 

### ISSUE THREAD

**Issue by joefast77** [meganz/android#180]
## General Information

- **MEGA Version:** 
6.2 (427)
- **OS Version(s):** 
Android 10
- **Devices/Simulators:** 
Huawei Nova 5T
- **Reproducible? (Yes/No):** 
Yes
##  What happened?
When in gallery mode one or two videos will play after selecting them but then nothing will ever play when exiting gallery mode they will play with no issue. 
## What did you expect to happen?
...

**Comment by joefast77** [comment]
android 10

**Comment by joefast77** [comment]
android 10, device huawei nova5t, app version 6.2 (427)
The issue is when gallery mode, when selecting a video file to play it will play for the first two or three videos i play then trying to select any video after that it will not play at all, will have to go out of the gallery mode and get back in for any video to play.

**Comment by javiergm1983** [comment]
Please could you provide a screen recording reproducing the issue? Thanks.

**Comment by joefast77** [comment]
https://user-images.githubusercontent.com/80571759/155310220-54a31d4f-07ac-44c3-a315-3b2f81b87af9.mp4

**Comment by joefast77** [comment]
this only happens in gallery mode the next video you choose will not play, but if you get out of gallery mode all videos play just fine

**Comment by javiergm1983** [comment]
Thanks for the screen recording, now I can clearly understand what is the issue and also have achieved to reproduce it. We will investigate the cause in order to try fix it in a future app version.

**Comment by joefast77** [comment]
thank you for your patience with me, i hope so.
