### ISSUE TITLE
Different image is previewed than the one tapped in offline mode

### ISSUE THREAD

**Issue by tackme31** [meganz/android#188]
## General Information

- **MEGA Version:** 
6.6 (433)

- **OS Version(s):** 
Android 12

- **Devices/Simulators:** 
Pixel 5

- **Reproducible? (Yes/No):** 
Yes

##  What happened?
When there are multiple images on the same level in offline mode, the tapped image is not previewed. Instead, the first image in the folder is previewed.

### how to reproduce
1. Delete all offline images and caches.
1. Upload two images to the same folder hierarchy.
1. Check "Available Offline" on both images.
1. Tap the second image displayed in offline mode.

## What did you expect to happen?
The tapped image should be previewed.

**Comment by javiergm1983** [comment]
We will take a look. Thanks for reporting.

**Comment by javiergm1983** [comment]
Hi again, we have already fixed this issue in v6.7 which will be available in the following days. Please check it again once you receive that update. Thanks.

**Comment by javiergm1983** [comment]
Hi @tackme31 we have started today the live roll out of the v6.7 which contains a fix for your issue.
Please, could you confirm here that the issue is solved when you receive that update? Thanks.

**Comment by tackme31** [comment]
Thank you for your kind support. I will respond again as soon as we confirm.

**Comment by tackme31** [comment]
I have received the latest update and confirmed that this issue has been fixed.
Thank you.
