### ISSUE TITLE
2fa paste

### ISSUE THREAD

**Issue by bingoxo** [meganz/android#191]
2fa codes can't be pasted into the app , only the first digit is pasted , unlike ios app

**Comment by angelds-mega** [comment]
Hello, we cannot replicate the issue. We have successfully pasted the complete 2fa code 3 times. 

Can you please tell us which device are you using? which OS and app version? 

If you experience app issues, the best course of action is:

- Un-install the app
- Re-install the app
- Log in again
- Try and see if it works

If it still doesn't work, please restart the device and perform the steps again.

**Comment by bingoxo** [comment]
i found out source of the issue , i was using clipboard function of the keyboard and it only pasted the first digit , but hard pressing to paste works fine , i'm not sure if the issue is from your side or google keyboard's side , either way , i'm closing the issue
