### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by lihe052g** [meganz/android#198]
##  What happened?
Hi guys, I am building the application according to Readme.md, but I can not download anything from the link https://mega.nz/file/A4pxxQoJ#OoAuL0SKIGuWkw6iSrSPHRMF0-Ri7BSF64IDeIWq-qs, pls check it. By the way, another link https://mega.nz/#!1tcl3CrL!i23zkmx7ibnYy34HQdsOOFAPOqQuTo1-2iZ5qFlU7-k has the same problem.

## What did you expect to happen?
...

**Comment by javiergm1983** [comment]
Hi @lihe052g I've just downloaded both links content and there is no problem, so probably there is an issue in your network. Please try again. Thanks.

**Comment by lihe052g** [comment]
Ok, thanks. I will check my network.

**Comment by lihe052g** [comment]
Hi @javiergm1983  I have another problem, I see "dist-build/android-armv7-a.sh &>> ${LOG_FILE}" in build.sh, but the file android-armv7-a.sh does not exist.
