### ISSUE TITLE
The app doesn't upload some photos

### ISSUE THREAD

**Issue by haael** [meganz/android#207]
## General Information

When selecting upload photos from camera (default folder), 2 bugs happen:

1. The app starts dozens of transfers at once, but will hardly finish any. Every transfer will get restarted every couple of minutes. The overall progress indicator will go forward then retract. Enabling option "do not use HTTP" doesn't change anything.
2. Many photos from camera are missing. I can not see them through Mega, despite they are available from a file manager. If a photo is not visible through Mega, it will also not be uploaded. Approx. 60% of photos are missing and I don't see any pattern why.

I don't know if the bugs are related.

- **MEGA Version:** 

6.20 (477)

- **OS Version(s):** 

Android 11

- **Devices/Simulators:** 

Ulefone, model Note 10.

- **Reproducible? (Yes/No):** 

##  What happened?

Selected upload files from camera, some photos are skipped, other upload extremely slow.

## What did you expect to happen?

All photos from camera uploaded to the cloud at wire speed.

**Comment by jx-mega** [comment]
In order to look further into your account status, please email us at support@mega.nz from your MEGA account email address so we can check for you.

**Comment by konnovdev** [comment]
The camera uploads engine is all revamped now, it previously used a legacy service and had a lot of bugs.

**Comment by haael** [comment]
OK, I can confirm the version 8.6 uploaded all the photos from my album. Good job and thank you.
