### ISSUE TITLE
Text file editor only allows to edit the first page in long files

### ISSUE THREAD

**Issue by dmell** [meganz/android#214]
## General Information

- **MEGA Version:** 7.8.1

- **OS Version(s):** 12

- **Devices/Simulators:** N/A

- **Reproducible? (Yes/No):** Yes

##  What happened?
The issue can be reproduced by uploading a long txt file. In my tests, ~70 kB did the job. What is important is that the file is displayed in multiple pages by the text viewer. If then we try to edit the file, we can only write at the end of the first page, and changes will end up in between the last line of the first page and the first line of the second.

## What did you expect to happen?
I expected to be able to edit the file entirely. Alternatively, if behind this issue there is an architectural problem, I would expect an error to be shown, warning the user that they cannot edit files longer than X.

**Comment by jx-mega** [comment]
Hello,

Thanks for the feedback but we are not able to reproduce the problem.

Could you update to the latest version 8.6 and try again? If the issue persists, please email us at support@mega.nz from your MEGA account email address with the details and screenshots showing the issue.

We will be able to check your account status from there also.

**Comment by dmell** [comment]
Hello,

I just checked again and the problem seems to have been solved. Thanks for your support!
