### ISSUE TITLE
Classpath Pollution with Showkase Library

### ISSUE THREAD

**Issue by esafirm** [meganz/android#225]
Hi team, thanks for making the code public, a lot of things can be learned from this repo.

---

I want to report that the `ShowkaseBrowserActivity` from the [showkase](https://github.com/airbnb/Showkase) library is carried to the release APK, I assume that this is not intended since I cannot see that you declared the `ShowkaseProvider` class in your keep rules. It might be a case of classpath pollution. 

I think we can make it a certain build type dependency to solve the problem or make it accessible through specific build type source set only.

Also, a shameless plug, you might want to check out [Compose UI Book](https://github.com/esafirm/compose-ui-book) an alternative for showkase that supports Compose Multiplatform!

**Comment by konnovdev** [comment]
Hi, thanks for the feedback! Actually we are removing showkase library in the next release (we haven't really used it)
