### ISSUE TITLE
Why is there a banner advertisement on the bottom of the Android mobile app?

### ISSUE THREAD

**Issue by FlawlessCasual17** [meganz/android#246]
Could someone please explain why such a thing even exists in the mega Android mobile app?

![Screenshot_20240509_105416_MEGA.jpg](https://github.com/meganz/android/assets/101912712/6058e5fb-981f-486d-bca0-50897553e48d)

**Comment by tt-mega** [comment]
Hello,

Thank you for your support and thank you for using MEGA.

The introduction of ads helps us to keep the free plan version available and to continue offering a quality service without charges.

If you prefer an ad-free experience, please visit https://mega.nz/pro and check out our plans and the available payment methods. By upgrading to a MEGA Pro plan, you won't see any ads and you will gain access to additional features.

Please note that depending on your location, and if you don't have a paid plan, cookies may be used by us and our approved advertising partners to customize adverts.
You can control your cookie settings by opening MEGA on the browser and navigating to https://mega.io/es/mega-io-cookie#cookie-settings-dialog
Disabling cookies won't eliminate ads entirely, but it will prevent them from being customized based on your online behaviour.

We value your privacy, and we use cookies to make sure your experience on our site is top-notch. We want to be totally upfront about what we're doing and give you the power to control your preferences.

**Comment by FlawlessCasual17** [comment]
Am I allowed to create a distribution of this android application with the ads removed?
