### ISSUE TITLE
v14.8-gms-release.apk is only 80 Bytes in size

### ISSUE THREAD

**Issue by dandare1980** [meganz/android#273]
### Environment:
- MEGA app Version(s): 14.8
- Devices/Simulators: Github releases web page

### Describe the bug
APK release is only 80 bytes in size and not functional.

### Reproduction Steps
Add the different steps to reproduce the behaviour.
1. Go to 'https://github.com/meganz/android/releases/tag/v14.8'
2. Click on 'v14.8-gms-release.apk'

### Expected behavior
APK is normally over 200mb in size.

### Screenshots / Logs
![v14 8-gms-release](https://github.com/user-attachments/assets/209795e1-92cb-4a1e-8069-d90db53c0155)

**Comment by robinshi-mega** [comment]
Thank you for reporting this @dandare1980. 
We will fix this.

**Comment by robinshi-mega** [comment]
Hi @dandare1980, we have uploaded the correct APK files for v14.8. 
Thanks again for reporting this.
