### ISSUE TITLE
Not possible to select multiple items for upload

### ISSUE THREAD

**Issue by bauxi** [meganz/android#5]
### Problem

When I click on Upload ..., Picture and choose my gallery app (or any other that is shown here), it is not possible to select multiple pictures for upload. That is quite annoying if I wanted to upload more than one picture at once. It is possible to select them from the file system, but for more "unexperienced" users it would be great to select it from the gallery app.
### Expected behavior

It should be possible to select multiple pictures for uploading by long pressing them.
### Test environment
- Phone: Fairphone 1U
- Android 4.2.2
- Mega Version 3.0.11.2

**Comment by d0x360** [comment]
It's probably not there because it has an automatic picture upload option but I do agree with you.

**Comment by tletum13** [comment]
select multiple items for upload has an automatic picture upload option but I do agree

**Comment by sawft99** [comment]
This appears to be a feature now. Close?

**Comment by bauxi** [comment]
Yeah, you are right!
