### ISSUE TITLE
Nexus 5 download error

### ISSUE THREAD

**Issue by shehzaman** [meganz/android#6]
Trying to download files to local device folder and everytime I get a network error, on wifi or mobile data.

Looked at the settings menu. Tried to change the default path from storage/emulated/0/MEGA/MEGA Downloads 

Received a pop-up window error. "ERROR Filesystem Problem". 

Checked the box for "Always ask for download location" 

Attempted to download another file - received the same error - "ERROR Filesystem Problem". 

MEGA SDK version - 970e65b

App version - 3.0.11.3

**Comment by bkobeszko** [comment]
I've experienced the same problem. I have Xperia S with nAOSP Android 6.0. I think that the problem exists on every Android with only internal memory.
I've modified the code and have added the _READ_EXTERNAL_STORAGE_ permission with no luck. The app has the necessary permissions.
When the path _/storage/emulated/0/MEGA/MEGA Downloads_ is created manually, the error is still popping out.
When I switched to the nAOSP 7 (Nougat), then I had the same problem, but then I had at least image thumbnails.

The good news is, that I built the app from revision a5555154 (2016-05-09), and app is working fine, the message is not prompted anymore and everything works fine. You can download this build from https://mega.nz/#!54pV3AqQ!uYIHVp7Xwpc72EzR1rq2tLer2OQexOKLZjXn6Izhnro or build on your own, just revert to the revision a5555154.

Anyway, the bug still exists in newest version.

**Comment by shehzaman** [comment]
Thank you for the build! 

Just gave it a shot today on my Nexus 5 running stock 6.0.1. 
Version [`a555515`](https://github.com/meganz/android/commit/a555515428dae134ccf9d3eb1910b9db972b685e) works well, tested multiple downloads on my phone.

**Comment by bkobeszko** [comment]
Hi @shehzaman, a555515 works, but the newest version still has the bug.
You should not close the issue.
