### ISSUE TITLE
How to get or generate the missing files ?

### ISSUE THREAD

**Issue by johnx32** [meganz/android#63]
Hi guys
I want to know how to obtain or generate some files that do not appear when cloning the project (due to the .gitignore)

Most of the files are from the MegaChat project but it does not tell me how to generate it either,
help please without that I can not compile the project
there are the files but in c ++ (.h .cpp) but I do not know how to use them or transform them into .java

MegaChatApi.java
MegaChatError.java
MegaChatRequest.java
MegaContactRequest.java
MegaEvent.java
MegaAccountSession.java
MegaChatCall.java
MegaChatError.java
MegaChatMessage.java
MegaChatRequest.java
MegaChatRoom.java
MegaHandleList.java
CameraSyncService.java
MegaUserAlert.java
MegaContactRequest.java
etc

**Comment by sergiohs84** [comment]
Please, see https://github.com/meganz/MEGAchat/issues/530#issuecomment-449080182

**Comment by johnx32** [comment]
Well
I could solve it alone, download all the Ndk and I worked with the ndkr14, it was the biggest problem, then everything went well, only that in megaApi everything comes out with red as if it contained an error but compiles without problems, I imagine it must be a problem of the IDE , everything else good and happy

**Comment by pingothedoer** [comment]
Hi, i have followed every step but still couldn't generate the files. Just for testing, i added some **echo** to check where it get stops. 

Here is the code:

_function createMEGAchatBindings
{
    echo "* Creating MEGAchat Java bindings"
    mkdir -p ../java/nz/mega/sdk
    echo "Dir created"
    swig -c++ -Imega/sdk/include -Imegachat/sdk/src/ -java -package nz.mega.sdk -outdir ${JAVA_OUTPUT_PATH}/nz/mega/sdk/ -o bindings/megachat.cpp megachat/sdk/bindings/megachatapi.i &>> ${LOG_FILE}
    echo "swig done"
    pushd megachat/sdk/src &>> ${LOG_FILE}
    echo "pushed"
    cmake -P genDbSchema.cmake
    echo "cmake done"
    popd &>> ${LOG_FILE}
    echo "popd done"
}_

And here is the result

<pre><font color="#8AE234"><b>pingo@pingo-Inspiron-5570</b></font>:<font color="#729FCF"><b>~/AndroidStudioProjects/MegaClient/android/app/src/main/jni</b></font>$ ./build.sh all
* Creating MEGAchat Java bindings
Dir created
<font color="#8AE234"><b>pingo@pingo-Inspiron-5570</b></font>:<font color="#729FCF"><b>~/AndroidStudioProjects/MegaClient/android/app/src/main/jni</b></font>$ </pre>

I have swig , java, ndk, android studio, every thing is installed. 
<pre>SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre
</pre>
