### ISSUE TITLE
is free software?

### ISSUE THREAD

**Issue by theScrabi** [meganz/android#8]
Is this app using any non-free libraries (besides the google-play-wallet)?

**Comment by dimqua** [comment]
[Firebase Cloud Messaging](https://github.com/meganz/android/blob/master/app/build.gradle#L62).

**Comment by theScrabi** [comment]
Ow yes this can be closed anyway. I thought this was free software, but its just OpenSource. This means that using this code is legally restricted, and I can't use it for what I wanted it to use.
